version: '3.8'
 
services:
  mysql:
    image: mysql:8
    container_name: mysql-adonis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: p-dev-unesco
      TZ: UTC
    ports:
      - "3306:3306"
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: projet-adonis
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
